# Generated by Django 4.2.7 on 2026-05-06 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_type',
            field=models.CharField(choices=[('pieces', 'Pieces'), ('bottles', 'Bottles'), ('boxes', 'Boxes'), ('sets', 'Sets'), ('liters', 'Liters'), ('ml', 'Milliliters'), ('grams', 'Grams'), ('kg', 'Kilograms')], default='pieces', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
