# Generated by Django 4.2.7 on 2026-05-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(default='Lusaka', max_length=100)),
                ('country', models.CharField(default='Zambia', max_length=100)),
                ('timezone', models.CharField(default='Africa/Lusaka', max_length=50)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('time_format', models.CharField(default='12h', max_length=10)),
                ('currency', models.CharField(default='ZMW', max_length=10)),
                ('currency_symbol', models.CharField(default='ZMW', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='18:00')),
                ('working_days', models.JSONField(default=list)),
                ('booking_buffer', models.IntegerField(default=15)),
                ('max_bookings_per_slot', models.IntegerField(default=3)),
                ('cancellation_policy', models.TextField(default='24 hours notice required for cancellation')),
                ('allow_online_booking', models.BooleanField(default=True)),
                ('require_deposit', models.BooleanField(default=True)),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_reminders', models.BooleanField(default=True)),
                ('booking_confirmations', models.BooleanField(default=True)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('review_notifications', models.BooleanField(default=True)),
                ('inventory_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salon Settings',
                'verbose_name_plural': 'Salon Settings',
                'db_table': 'salon_settings',
            },
        ),
    ]
