# Generated by Django 4.2.7 on 2026-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonsettings',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address', null=True),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='allow_online_booking',
            field=models.BooleanField(default=True, help_text='Enable online booking'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='booking_buffer',
            field=models.IntegerField(default=15, help_text='Buffer time between bookings in minutes'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='booking_confirmations',
            field=models.BooleanField(default=True, help_text='Send booking confirmation emails'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='cancellation_policy',
            field=models.TextField(default='24 hours notice required for cancellation', help_text='Cancellation policy text'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='closing_time',
            field=models.TimeField(default='18:00', help_text='Business closing time'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='country',
            field=models.CharField(default='Zambia', help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='currency',
            field=models.CharField(default='ZMW', help_text='Currency code (ZMW, USD, etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='currency_symbol',
            field=models.CharField(default='ZMW', help_text='Currency symbol', max_length=10),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='date_format',
            field=models.CharField(default='DD/MM/YYYY', help_text='Date display format', max_length=20),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='deposit_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Deposit percentage required', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='email',
            field=models.EmailField(default='info@salonpro.co.zm', help_text='Business email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='inventory_alerts',
            field=models.BooleanField(default=True, help_text='Notify on low inventory'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='marketing_emails',
            field=models.BooleanField(default=False, help_text='Send marketing/promotional emails'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='max_bookings_per_slot',
            field=models.IntegerField(default=3, help_text='Maximum bookings per time slot'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='opening_time',
            field=models.TimeField(default='08:00', help_text='Business opening time'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='phone',
            field=models.CharField(default='+260', help_text='Business phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='province',
            field=models.CharField(default='Lusaka', help_text='Province', max_length=100),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='require_deposit',
            field=models.BooleanField(default=True, help_text='Require deposit for bookings'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='review_notifications',
            field=models.BooleanField(default=True, help_text='Notify on new reviews'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='salon_name',
            field=models.CharField(default='SalonPro', help_text='Name of your salon', max_length=200),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='sms_reminders',
            field=models.BooleanField(default=True, help_text='Enable SMS reminders'),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=16.0, help_text='VAT/Tax rate percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='time_format',
            field=models.CharField(default='12h', help_text='Time display format (12h or 24h)', max_length=10),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='timezone',
            field=models.CharField(default='Africa/Lusaka', help_text='Timezone for the business', max_length=50),
        ),
        migrations.AlterField(
            model_name='salonsettings',
            name='working_days',
            field=models.JSONField(default=list, help_text='List of working days'),
        ),
    ]
